export enum USER_ACTION_TYPES {
    SET_CURRENT_USER = 'users/SET_CURRENT_USER',
    LOGIN_LOADING = 'users/LOGIN_LOADING',
    LOGIN_SUCCESS = 'users/LOGIN_SUCCESS',
    LOGIN_FAILED = 'users/LOGIN_FAILED',
    SIGNUP_LOADING = 'users/SIGNUP_LOADING',
    SIGNUP_SUCCESS = 'users/SIGNUP_SUCCESS',
    SIGNUP_FAILED = 'users/SIGNUP_FAILED',
    LOGOUT_USER = 'users/LOGOUT_USER'
}