export enum PROFILE_ACTION_TYPES {
    FETCH_PROFILE_BY_USERNAME_LOADING = "profiles/FETCH_PROFILE_BY_USERNAME_LOADING",
    FETCH_PROFILE_BY_USERNAME_SUCCESS = "profiles/FETCH_PROFILE_BY_USERNAME_SUCCESS",
    FETCH_PROFILE_BY_USERNAME_FAILED = "profiles/FETCH_PROFILE_BY_USERNAME_FAILED",
    UPLOAD_DOCUMENT_LOADING = "profiles/UPLOAD_DOCUMENT_LOADING",
    UPLOAD_DOCUMENT_SUCCESS = "profiles/UPLOAD_DOCUMENT_SUCCESS",
    UPLOAD_DOCUMENT_FAILED = "profiles/UPLOAD_DOCUMENT_FAILED",
}