export enum PROFILE_ACTION_TYPES {
    FETCH_PROFILE_BY_USERNAME_LOADING = "profiles/FETCH_PROFILE_BY_USERNAME_LOADING",
    FETCH_PROFILE_BY_USERNAME_SUCCESS = "profiles/FETCH_PROFILE_BY_USERNAME_SUCCESS",
    FETCH_PROFILE_BY_USERNAME_FAILED = "profiles/FETCH_PROFILE_BY_USERNAME_FAILED",
    UPLOAD_DOCUMENT_LOADING = "profiles/UPLOAD_DOCUMENT_LOADING",
    UPLOAD_DOCUMENT_SUCCESS = "profiles/UPLOAD_DOCUMENT_SUCCESS",
    UPLOAD_DOCUMENT_FAILED = "profiles/UPLOAD_DOCUMENT_FAILED",
    DELETE_DOCUMENT_LOADING = "profiles/DELETE_DOCUMENT_LOADING",
    DELETE_DOCUMENT_SUCCESS = "profiles/DELETE_DOCUMENT_SUCCESS",
    DELETE_DOCUMENT_FAILED = "profiles/DELETE_DOCUMENT_FAILED",
    DOCUMENT_TO_MAIN_LOADING = "profiles/DOCUMENT_TO_MAIN_LOADING",
    DOCUMENT_TO_MAIN_SUCCESS = "profiles/DOCUMENT_TO_MAIN_SUCCESS",
    DOCUMENT_TO_MAIN_FAILED = "profiles/DOCUMENT_TO_MAIN_FAILED",
}