export enum PROFILE_ACTION_TYPES {
    FETCH_PROFILE_BY_USERNAME_LOADING = "profiles/FETCH_PROFILE_BY_USERNAME_LOADING",
    FETCH_PROFILE_BY_USERNAME_SUCCESS = "profiles/FETCH_PROFILE_BY_USERNAME_SUCCESS",
    FETCH_PROFILE_BY_USERNAME_FAILED = "profiles/FETCH_PROFILE_BY_USERNAME_FAILED",
}